server:
  port: 9527
spring:
  application:
    name: auth-server
  security:
    user:
      name: ailuoli
      password: 961226
  redis:
    database: 2
    host: 101.37.174.133
    port: 1235
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:8761/eureka/   #\u670D\u52A1\u6CE8\u518C\u4E2D\u5FC3\u5730\u5740

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

druid:
  datasource:
    defaultName: datasource1
    datasource1:
      url: jdbc:mysql://101.37.174.133:1234/cloud_blog?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
      username: root
      password: Ws961226
      driverClassName: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true




